### ISSUE TITLE
Version control

### ISSUE THREAD

**Issue by favoyang** [JimmyCushnie/JimmysUnityUtilities#1]
Hi @JimmyCushnie,

Thanks for making this awesome UPM package. I'm the creator of the OpenUPM platform, an open-source UPM registry, and continuous build service based on Git tags. It's hosting more than 200+ open-source UPM packages at the time of writing.

To make it happen, I would suggest you make GitHub releases (which create Git tags) for version control. It can be achieved either manually or using [an automatic approach](https://medium.com/openupm/how-to-maintain-upm-package-part-2-f352fbf5f87c).

After your GitHub release, our build pipelines will detect the changes and build UPM packages in 5-10 minutes. Then you can visit your package at https://openupm.com/packages/com.jimmycushnie.jimmysunityutilities/

If this makes sense for you, feel free to create Git tags for other your packages
- https://openupm.com/packages/com.jimmycushnie.intersucc/
- https://openupm.com/packages/com.jimmycushnie.persistentdata/

**Comment by JimmyCushnie** [comment]
JUU is a very chaotic project that I'm constantly changing and updating. APIs break on a weekly basis. I don't think such a project is suited for versioned package management.

Regardless, I went ahead and made a release, and I guess I'll make a new one every so often.

**Comment by favoyang** [comment]
> JUU is a very chaotic project that I'm constantly changing and updating. APIs break on a weekly basis. I don't think such a project is suited for versioned package management.

Then maybe it should be removed from OpenUPM? If you preferred.

**Comment by JimmyCushnie** [comment]
I really don't care whether it's on OpenUPM, that's up to the OpenUPM people. You're the one who came to *me* asking for help putting it there lol.

**Comment by favoyang** [comment]
Got it. Then I will leave it here. Thanks for your comment.
